<h2> NumPy (Numeric Python) </h2>

<b> Python Arrays </b>

In [1]:
import array
my_array = array.array('i', [1,2,3,4,5])

In [2]:
my_array

array('i', [1, 2, 3, 4, 5])

In [3]:
type(my_array)

array.array

In [4]:
my_floatarray = array.array('f', [1.2,3.6])

In [5]:
type(my_floatarray)

array.array

<b> NumPy arrays </b>

In [6]:
import numpy as np

In [7]:
list1 = [1,3,4,6,8,9]
np.array(list1)

array([1, 3, 4, 6, 8, 9])

In [8]:
list1 = [1,3,6,2,40,1]
my_integer_nparray = np.array(list1)
my_integer_nparray

array([ 1,  3,  6,  2, 40,  1])

In [9]:
type(my_integer_nparray)

numpy.ndarray

In [10]:
float_list = [1.3,4.5,7.4,2.3]
np_arratFloat = np.array(float_list)
np_arratFloat

array([1.3, 4.5, 7.4, 2.3])

In [11]:
type(np_arratFloat)

numpy.ndarray

In [12]:
mix_list = [1,2,4.5,'a']
np_mixedarray = np.array(mix_list)
np_mixedarray

array(['1', '2', '4.5', 'a'], dtype='<U32')

In [13]:
arr = np.array([1,2,3,4])

In [14]:
arr


array([1, 2, 3, 4])

In [15]:
#0D array (scalar elements)

zero_array = np.array(50)
zero_array

array(50)

In [16]:
type(zero_array)

numpy.ndarray

In [17]:
#1D Array - unidimentional

one_array = np.array([1,2,3])
one_array


array([1, 2, 3])

In [18]:
type(one_array)

numpy.ndarray

In [20]:
#2d array - matrix

twod_array = np.array([[1,2,3], [4,5,6]])
twod_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
my_list = one_array.tolist()

In [22]:
my_list

[1, 2, 3]

In [23]:
type(my_list)

list

<b> Properties of numpy array </b>

In [24]:
my_np_array = np.array([1,2,4,8,5])

In [25]:
my_np_array

array([1, 2, 4, 8, 5])

In [26]:
type(my_np_array)

numpy.ndarray

In [27]:
my_np_array.dtype

dtype('int32')

In [28]:
my_np_array.ndim

1

In [29]:
my_np_array.shape

(5,)

In [30]:
my_np_array.size

5

<b> Pre-populate arrays </b> 

In [31]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [32]:
zeros.dtype

dtype('float64')

In [33]:
zeros_int = np.zeros(5,dtype=int)
zeros_int

array([0, 0, 0, 0, 0])

In [34]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.empty(7)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.60218491e-306,
       6.23053614e-307, 2.22526399e-307, 2.05837348e-312])

In [36]:
arange_array = np.arange(1,10)
arange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a1 = np.arange(5,100,5)
a1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

<b> 2D arrays </b>

In [38]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

two_d_array = np.array([l1,l2,l3])
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
two_d_array.dtype

dtype('int32')

In [40]:
two_d_array.ndim

2

In [41]:
two_d_array.shape

(3, 3)

In [42]:
two_d_array.size

9

<b> NumPy Computations </b> 

In [43]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [44]:
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> Ways to access the array elements </b> 

In [45]:
a1

array([1, 2, 3, 4, 5])

In [46]:
a1[0]

1

In [47]:
a1[2]

3

In [48]:
a1[-1]

5

In [49]:
a1[3] = 333

In [50]:
a1

array([  1,   2,   3, 333,   5])

In [51]:
a1[1:]

array([  2,   3, 333,   5])

In [52]:
a_sub = a1[:3]
a_sub

array([1, 2, 3])

In [53]:
type(a_sub)

numpy.ndarray

In [54]:
a1

array([  1,   2,   3, 333,   5])

In [55]:
a_sub

array([1, 2, 3])

In [56]:
a_sub[0] = 45

In [57]:
a_sub

array([45,  2,  3])

In [58]:
a1

array([ 45,   2,   3, 333,   5])

In [59]:
a2 = a1.view()

In [60]:
a2

array([ 45,   2,   3, 333,   5])

In [61]:
a1[0] = 100

In [62]:
a1

array([100,   2,   3, 333,   5])

In [63]:
a2

array([100,   2,   3, 333,   5])

In [64]:
a_copy = a1.copy()

In [65]:
a_copy

array([100,   2,   3, 333,   5])

In [66]:
a_copy[1] = 200

In [67]:
a_copy

array([100, 200,   3, 333,   5])

In [68]:
a1

array([100,   2,   3, 333,   5])

In [69]:
one_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [70]:
one_array.dtype

dtype('int32')

In [71]:
one_array.ndim

1

In [72]:
reshaped_array = one_array.reshape(4,3)
reshaped_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
reshaped_array.ndim

2

In [74]:
reshaped_array1 = one_array.reshape(3,4)
reshaped_array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<b> Computation - arti </b> 

In [75]:
a1

array([100,   2,   3, 333,   5])

In [76]:
sum(a1)

443

In [77]:
np.sum(a1)

443

In [78]:
# exercise - Randomly generate 1lakh elements , np.random.randint()
# using sum() and also np.sum() - Answers will be the same but compare the timing!! 
# %timeit

In [79]:
a1

array([100,   2,   3, 333,   5])

In [80]:
a1 + 5

array([105,   7,   8, 338,  10])

In [81]:
a1 ** 2

array([ 10000,      4,      9, 110889,     25])

In [82]:
np.add(a1,5)

array([105,   7,   8, 338,  10])

In [83]:
a1

array([100,   2,   3, 333,   5])

In [84]:
a1

array([100,   2,   3, 333,   5])

In [85]:
a1 == 3

array([False, False,  True, False, False])

In [86]:
a1 !=10000


array([ True,  True,  True,  True,  True])

In [87]:
np.sum(a1 == 3)

1

In [88]:
np.sum(a1<500)

5

In [89]:
a1

array([100,   2,   3, 333,   5])

In [90]:
np.sum(a1<300)

4

In [92]:
np.any(a1 > 3000)

False

In [93]:
a1.max()

333

In [94]:
a1.min()

2

In [95]:
a1.std()

127.81017173918512

In [96]:
a1.mean()

88.6

In [97]:
a2

array([100,   2,   3, 333,   5])

In [98]:
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.sum(two_d_array,axis=0)

array([12, 15, 18])

In [101]:
np.any((a1 > 5) & (a1<100))

False

In [102]:
# Linear Algebra using NP Array

#Fruit seller sold 20 mangoes nad 10 oranges on Friday for a total of Rs.350. He sold 17 mangoes and 22 oranges 
#for Rs. 500 on Sat. Price of fruits dint change both days. Whats the price os 1 mango and 1 orange ? 

# x = mangoes , y = oranges 

# 20x + 10y = 350
# 17x + 22y = 500 

A = np.array([[20,10],[17,22]])
B = np.array([350,500])


In [103]:
X = np.linalg.solve(A,B)
print(X)

[10. 15.]


In [105]:
X = np.array([[1,2],[3,4]])
print(X)
X.transpose()

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

In [106]:
X = np.eye(3)

In [107]:
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.sum(a1 < 3000)

5

In [109]:
a1 < 3000

array([ True,  True,  True,  True,  True])

In [110]:
np.sum(a1)

443